//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Discovery) DeepCopyInto(out *Discovery) {
	*out = *in
	if in.NamespaceSelector != nil {
		in, out := &in.NamespaceSelector, &out.NamespaceSelector
		*out = new(v1.RouteNamespaces)
		(*in).DeepCopyInto(*out)
	}
	in.LabelSelector.DeepCopyInto(&out.LabelSelector)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Discovery.
func (in *Discovery) DeepCopy() *Discovery {
	if in == nil {
		return nil
	}
	out := new(Discovery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftBackendRef) DeepCopyInto(out *MinecraftBackendRef) {
	*out = *in
	in.BackendRef.DeepCopyInto(&out.BackendRef)
	out.DistributionStrategy = in.DistributionStrategy
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftBackendRef.
func (in *MinecraftBackendRef) DeepCopy() *MinecraftBackendRef {
	if in == nil {
		return nil
	}
	out := new(MinecraftBackendRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftDistributionStrategy) DeepCopyInto(out *MinecraftDistributionStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftDistributionStrategy.
func (in *MinecraftDistributionStrategy) DeepCopy() *MinecraftDistributionStrategy {
	if in == nil {
		return nil
	}
	out := new(MinecraftDistributionStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackFilterRule) DeepCopyInto(out *MinecraftFallbackFilterRule) {
	*out = *in
	out.MinecraftFilterRule = in.MinecraftFilterRule
	in.FallbackFor.DeepCopyInto(&out.FallbackFor)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackFilterRule.
func (in *MinecraftFallbackFilterRule) DeepCopy() *MinecraftFallbackFilterRule {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackFilterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackFilterRuleSet) DeepCopyInto(out *MinecraftFallbackFilterRuleSet) {
	*out = *in
	out.MinecraftFilterRuleSet = in.MinecraftFilterRuleSet
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MinecraftFallbackFilterRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackFilterRuleSet.
func (in *MinecraftFallbackFilterRuleSet) DeepCopy() *MinecraftFallbackFilterRuleSet {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackFilterRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackRoute) DeepCopyInto(out *MinecraftFallbackRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackRoute.
func (in *MinecraftFallbackRoute) DeepCopy() *MinecraftFallbackRoute {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftFallbackRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackRouteList) DeepCopyInto(out *MinecraftFallbackRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinecraftFallbackRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackRouteList.
func (in *MinecraftFallbackRouteList) DeepCopy() *MinecraftFallbackRouteList {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftFallbackRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackRouteSpec) DeepCopyInto(out *MinecraftFallbackRouteSpec) {
	*out = *in
	in.MinecraftRoute.DeepCopyInto(&out.MinecraftRoute)
	if in.FilterRules != nil {
		in, out := &in.FilterRules, &out.FilterRules
		*out = make([]MinecraftFallbackFilterRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackRouteSpec.
func (in *MinecraftFallbackRouteSpec) DeepCopy() *MinecraftFallbackRouteSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFallbackRouteStatus) DeepCopyInto(out *MinecraftFallbackRouteStatus) {
	*out = *in
	in.RouteStatus.DeepCopyInto(&out.RouteStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFallbackRouteStatus.
func (in *MinecraftFallbackRouteStatus) DeepCopy() *MinecraftFallbackRouteStatus {
	if in == nil {
		return nil
	}
	out := new(MinecraftFallbackRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFilterRule) DeepCopyInto(out *MinecraftFilterRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFilterRule.
func (in *MinecraftFilterRule) DeepCopy() *MinecraftFilterRule {
	if in == nil {
		return nil
	}
	out := new(MinecraftFilterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftFilterRuleSet) DeepCopyInto(out *MinecraftFilterRuleSet) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftFilterRuleSet.
func (in *MinecraftFilterRuleSet) DeepCopy() *MinecraftFilterRuleSet {
	if in == nil {
		return nil
	}
	out := new(MinecraftFilterRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinFilterRule) DeepCopyInto(out *MinecraftJoinFilterRule) {
	*out = *in
	out.MinecraftFilterRule = in.MinecraftFilterRule
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinFilterRule.
func (in *MinecraftJoinFilterRule) DeepCopy() *MinecraftJoinFilterRule {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinFilterRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinFilterRuleSet) DeepCopyInto(out *MinecraftJoinFilterRuleSet) {
	*out = *in
	out.MinecraftFilterRuleSet = in.MinecraftFilterRuleSet
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]MinecraftJoinFilterRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinFilterRuleSet.
func (in *MinecraftJoinFilterRuleSet) DeepCopy() *MinecraftJoinFilterRuleSet {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinFilterRuleSet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinRoute) DeepCopyInto(out *MinecraftJoinRoute) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinRoute.
func (in *MinecraftJoinRoute) DeepCopy() *MinecraftJoinRoute {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftJoinRoute) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinRouteList) DeepCopyInto(out *MinecraftJoinRouteList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MinecraftJoinRoute, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinRouteList.
func (in *MinecraftJoinRouteList) DeepCopy() *MinecraftJoinRouteList {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinRouteList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MinecraftJoinRouteList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinRouteSpec) DeepCopyInto(out *MinecraftJoinRouteSpec) {
	*out = *in
	in.MinecraftRoute.DeepCopyInto(&out.MinecraftRoute)
	if in.FilterRules != nil {
		in, out := &in.FilterRules, &out.FilterRules
		*out = make([]MinecraftJoinFilterRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinRouteSpec.
func (in *MinecraftJoinRouteSpec) DeepCopy() *MinecraftJoinRouteSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinRouteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftJoinRouteStatus) DeepCopyInto(out *MinecraftJoinRouteStatus) {
	*out = *in
	in.RouteStatus.DeepCopyInto(&out.RouteStatus)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftJoinRouteStatus.
func (in *MinecraftJoinRouteStatus) DeepCopy() *MinecraftJoinRouteStatus {
	if in == nil {
		return nil
	}
	out := new(MinecraftJoinRouteStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftRoute) DeepCopyInto(out *MinecraftRoute) {
	*out = *in
	in.CommonRouteSpec.DeepCopyInto(&out.CommonRouteSpec)
	if in.BackendRefs != nil {
		in, out := &in.BackendRefs, &out.BackendRefs
		*out = make([]MinecraftBackendRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftRoute.
func (in *MinecraftRoute) DeepCopy() *MinecraftRoute {
	if in == nil {
		return nil
	}
	out := new(MinecraftRoute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftServer) DeepCopyInto(out *MinecraftServer) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftServer.
func (in *MinecraftServer) DeepCopy() *MinecraftServer {
	if in == nil {
		return nil
	}
	out := new(MinecraftServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftService) DeepCopyInto(out *MinecraftService) {
	*out = *in
	if in.Servers != nil {
		in, out := &in.Servers, &out.Servers
		*out = make(map[string]MinecraftServer, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.DistributionStrategy = in.DistributionStrategy
	if in.JoinRules != nil {
		in, out := &in.JoinRules, &out.JoinRules
		*out = make([]MinecraftJoinFilterRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FallbackRules != nil {
		in, out := &in.FallbackRules, &out.FallbackRules
		*out = make([]MinecraftFallbackFilterRuleSet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftService.
func (in *MinecraftService) DeepCopy() *MinecraftService {
	if in == nil {
		return nil
	}
	out := new(MinecraftService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfrastructure) DeepCopyInto(out *NetworkInfrastructure) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfrastructure.
func (in *NetworkInfrastructure) DeepCopy() *NetworkInfrastructure {
	if in == nil {
		return nil
	}
	out := new(NetworkInfrastructure)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkInfrastructure) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfrastructureList) DeepCopyInto(out *NetworkInfrastructureList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NetworkInfrastructure, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfrastructureList.
func (in *NetworkInfrastructureList) DeepCopy() *NetworkInfrastructureList {
	if in == nil {
		return nil
	}
	out := new(NetworkInfrastructureList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkInfrastructureList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfrastructureSpec) DeepCopyInto(out *NetworkInfrastructureSpec) {
	*out = *in
	in.Discovery.DeepCopyInto(&out.Discovery)
	in.Edge.DeepCopyInto(&out.Edge)
	in.Network.DeepCopyInto(&out.Network)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfrastructureSpec.
func (in *NetworkInfrastructureSpec) DeepCopy() *NetworkInfrastructureSpec {
	if in == nil {
		return nil
	}
	out := new(NetworkInfrastructureSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfrastructureStatus) DeepCopyInto(out *NetworkInfrastructureStatus) {
	*out = *in
	if in.BackendRefs != nil {
		in, out := &in.BackendRefs, &out.BackendRefs
		*out = make([]v1.BackendObjectReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfrastructureStatus.
func (in *NetworkInfrastructureStatus) DeepCopy() *NetworkInfrastructureStatus {
	if in == nil {
		return nil
	}
	out := new(NetworkInfrastructureStatus)
	in.DeepCopyInto(out)
	return out
}
