// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: network/v1alpha1/api.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteKind int32

const (
	RouteKind_ROUTE_KIND_JOIN     RouteKind = 0
	RouteKind_ROUTE_KIND_FALLBACK RouteKind = 1
)

// Enum value maps for RouteKind.
var (
	RouteKind_name = map[int32]string{
		0: "ROUTE_KIND_JOIN",
		1: "ROUTE_KIND_FALLBACK",
	}
	RouteKind_value = map[string]int32{
		"ROUTE_KIND_JOIN":     0,
		"ROUTE_KIND_FALLBACK": 1,
	}
)

func (x RouteKind) Enum() *RouteKind {
	p := new(RouteKind)
	*p = x
	return p
}

func (x RouteKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteKind) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1alpha1_api_proto_enumTypes[0].Descriptor()
}

func (RouteKind) Type() protoreflect.EnumType {
	return &file_network_v1alpha1_api_proto_enumTypes[0]
}

func (x RouteKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteKind.Descriptor instead.
func (RouteKind) EnumDescriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

type RouteResponse_Result int32

const (
	RouteResponse_RESULT_OK       RouteResponse_Result = 0
	RouteResponse_RESULT_NO_ROUTE RouteResponse_Result = 1
	RouteResponse_RESULT_REJECTED RouteResponse_Result = 2
)

// Enum value maps for RouteResponse_Result.
var (
	RouteResponse_Result_name = map[int32]string{
		0: "RESULT_OK",
		1: "RESULT_NO_ROUTE",
		2: "RESULT_REJECTED",
	}
	RouteResponse_Result_value = map[string]int32{
		"RESULT_OK":       0,
		"RESULT_NO_ROUTE": 1,
		"RESULT_REJECTED": 2,
	}
)

func (x RouteResponse_Result) Enum() *RouteResponse_Result {
	p := new(RouteResponse_Result)
	*p = x
	return p
}

func (x RouteResponse_Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteResponse_Result) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1alpha1_api_proto_enumTypes[1].Descriptor()
}

func (RouteResponse_Result) Type() protoreflect.EnumType {
	return &file_network_v1alpha1_api_proto_enumTypes[1]
}

func (x RouteResponse_Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteResponse_Result.Descriptor instead.
func (RouteResponse_Result) EnumDescriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{5, 0}
}

type PlayerPresenceEvent_Kind int32

const (
	PlayerPresenceEvent_KIND_CONNECTED    PlayerPresenceEvent_Kind = 0
	PlayerPresenceEvent_KIND_DISCONNECTED PlayerPresenceEvent_Kind = 1
)

// Enum value maps for PlayerPresenceEvent_Kind.
var (
	PlayerPresenceEvent_Kind_name = map[int32]string{
		0: "KIND_CONNECTED",
		1: "KIND_DISCONNECTED",
	}
	PlayerPresenceEvent_Kind_value = map[string]int32{
		"KIND_CONNECTED":    0,
		"KIND_DISCONNECTED": 1,
	}
)

func (x PlayerPresenceEvent_Kind) Enum() *PlayerPresenceEvent_Kind {
	p := new(PlayerPresenceEvent_Kind)
	*p = x
	return p
}

func (x PlayerPresenceEvent_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlayerPresenceEvent_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1alpha1_api_proto_enumTypes[2].Descriptor()
}

func (PlayerPresenceEvent_Kind) Type() protoreflect.EnumType {
	return &file_network_v1alpha1_api_proto_enumTypes[2]
}

func (x PlayerPresenceEvent_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlayerPresenceEvent_Kind.Descriptor instead.
func (PlayerPresenceEvent_Kind) EnumDescriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{6, 0}
}

// PlayerContext carries the proxy-side knowledge the controller needs to
// evaluate routing rules for a player. Permissions are pre-evaluated by the
// proxy against the required_permissions set most recently pushed in ServerSync.
type PlayerContext struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ConnectedDomain string                 `protobuf:"bytes,1,opt,name=connected_domain,json=connectedDomain,proto3" json:"connected_domain,omitempty"`
	Permissions     map[string]bool        `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerContext) Reset() {
	*x = PlayerContext{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerContext) ProtoMessage() {}

func (x *PlayerContext) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerContext.ProtoReflect.Descriptor instead.
func (*PlayerContext) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerContext) GetConnectedDomain() string {
	if x != nil {
		return x.ConnectedDomain
	}
	return ""
}

func (x *PlayerContext) GetPermissions() map[string]bool {
	if x != nil {
		return x.Permissions
	}
	return nil
}

// ProxyHello is the mandatory first message on a Connect stream. It identifies
// the proxy and the gateway listener it serves.
type ProxyHello struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProxyId          string                 `protobuf:"bytes,1,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	GatewayNamespace string                 `protobuf:"bytes,2,opt,name=gateway_namespace,json=gatewayNamespace,proto3" json:"gateway_namespace,omitempty"`
	GatewayName      string                 `protobuf:"bytes,3,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	ListenerName     string                 `protobuf:"bytes,4,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProxyHello) Reset() {
	*x = ProxyHello{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHello) ProtoMessage() {}

func (x *ProxyHello) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHello.ProtoReflect.Descriptor instead.
func (*ProxyHello) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyHello) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *ProxyHello) GetGatewayNamespace() string {
	if x != nil {
		return x.GatewayNamespace
	}
	return ""
}

func (x *ProxyHello) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *ProxyHello) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

type PresenceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Context       *PlayerContext         `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceEntry) Reset() {
	*x = PresenceEntry{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceEntry) ProtoMessage() {}

func (x *PresenceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceEntry.ProtoReflect.Descriptor instead.
func (*PresenceEntry) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{2}
}

func (x *PresenceEntry) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PresenceEntry) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PresenceEntry) GetContext() *PlayerContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// PresenceSnapshot replays every player currently connected to the proxy. It is
// sent immediately after ProxyHello so the controller can rebuild its presence
// map after a restart or leader failover.
type PresenceSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PresenceEntry       `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceSnapshot) Reset() {
	*x = PresenceSnapshot{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceSnapshot) ProtoMessage() {}

func (x *PresenceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceSnapshot.ProtoReflect.Descriptor instead.
func (*PresenceSnapshot) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{3}
}

func (x *PresenceSnapshot) GetPlayers() []*PresenceEntry {
	if x != nil {
		return x.Players
	}
	return nil
}

// RouteRequest asks the controller to pick a server for a player. The proxy
// blocks the join or fallback until the matching RouteResponse arrives.
type RouteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId     string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	PlayerUuid        string                 `protobuf:"bytes,2,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	Kind              RouteKind              `protobuf:"varint,3,opt,name=kind,proto3,enum=network.v1alpha1.RouteKind" json:"kind,omitempty"`
	Context           *PlayerContext         `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	CurrentServerName *string                `protobuf:"bytes,5,opt,name=current_server_name,json=currentServerName,proto3,oneof" json:"current_server_name,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{4}
}

func (x *RouteRequest) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RouteRequest) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *RouteRequest) GetKind() RouteKind {
	if x != nil {
		return x.Kind
	}
	return RouteKind_ROUTE_KIND_JOIN
}

func (x *RouteRequest) GetContext() *PlayerContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *RouteRequest) GetCurrentServerName() string {
	if x != nil && x.CurrentServerName != nil {
		return *x.CurrentServerName
	}
	return ""
}

type RouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Result        RouteResponse_Result   `protobuf:"varint,2,opt,name=result,proto3,enum=network.v1alpha1.RouteResponse_Result" json:"result,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{5}
}

func (x *RouteResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *RouteResponse) GetResult() RouteResponse_Result {
	if x != nil {
		return x.Result
	}
	return RouteResponse_RESULT_OK
}

func (x *RouteResponse) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

// PlayerPresenceEvent reports a player connecting to or disconnecting from a
// backend server, keeping the controller's presence map current in real time.
type PlayerPresenceEvent struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PlayerUuid    string                   `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	ServerName    string                   `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Kind          PlayerPresenceEvent_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=network.v1alpha1.PlayerPresenceEvent_Kind" json:"kind,omitempty"`
	Context       *PlayerContext           `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPresenceEvent) Reset() {
	*x = PlayerPresenceEvent{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPresenceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPresenceEvent) ProtoMessage() {}

func (x *PlayerPresenceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPresenceEvent.ProtoReflect.Descriptor instead.
func (*PlayerPresenceEvent) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{6}
}

func (x *PlayerPresenceEvent) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerPresenceEvent) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PlayerPresenceEvent) GetKind() PlayerPresenceEvent_Kind {
	if x != nil {
		return x.Kind
	}
	return PlayerPresenceEvent_KIND_CONNECTED
}

func (x *PlayerPresenceEvent) GetContext() *PlayerContext {
	if x != nil {
		return x.Context
	}
	return nil
}

// ServerPlayerCounts is reported periodically to reconcile drift between the
// proxy's view of player counts and the controller's presence map.
type ServerPlayerCounts struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CountsByServer map[string]uint32      `protobuf:"bytes,1,rep,name=counts_by_server,json=countsByServer,proto3" json:"counts_by_server,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerPlayerCounts) Reset() {
	*x = ServerPlayerCounts{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPlayerCounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPlayerCounts) ProtoMessage() {}

func (x *ServerPlayerCounts) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPlayerCounts.ProtoReflect.Descriptor instead.
func (*ServerPlayerCounts) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{7}
}

func (x *ServerPlayerCounts) GetCountsByServer() map[string]uint32 {
	if x != nil {
		return x.CountsByServer
	}
	return nil
}

// ServerSync is the full set of servers the proxy should have registered, plus
// the permissions it must evaluate for every RouteRequest and presence event.
type ServerSync struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Servers             []*ManagedServer       `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
	RequiredPermissions []string               `protobuf:"bytes,2,rep,name=required_permissions,json=requiredPermissions,proto3" json:"required_permissions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerSync) Reset() {
	*x = ServerSync{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerSync) ProtoMessage() {}

func (x *ServerSync) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerSync.ProtoReflect.Descriptor instead.
func (*ServerSync) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{8}
}

func (x *ServerSync) GetServers() []*ManagedServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ServerSync) GetRequiredPermissions() []string {
	if x != nil {
		return x.RequiredPermissions
	}
	return nil
}

// MoveCommand instructs the proxy to move one player, on behalf of a
// PlayerTransfer resource. command_id encodes the originating resource and
// player as "<namespace>/<name>#<playerUUID>#<attempt>".
type MoveCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	PlayerUuid    string                 `protobuf:"bytes,2,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	ServerName    string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCommand) Reset() {
	*x = MoveCommand{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCommand) ProtoMessage() {}

func (x *MoveCommand) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCommand.ProtoReflect.Descriptor instead.
func (*MoveCommand) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{9}
}

func (x *MoveCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MoveCommand) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *MoveCommand) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type MoveResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveResult) Reset() {
	*x = MoveResult{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveResult) ProtoMessage() {}

func (x *MoveResult) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveResult.ProtoReflect.Descriptor instead.
func (*MoveResult) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{10}
}

func (x *MoveResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MoveResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MoveResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// ProxyMessage is anything a proxy sends to the controller.
type ProxyMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ProxyMessage_Hello
	//	*ProxyMessage_PresenceSnapshot
	//	*ProxyMessage_RouteRequest
	//	*ProxyMessage_PresenceEvent
	//	*ProxyMessage_PlayerCounts
	//	*ProxyMessage_MoveResult
	Message       isProxyMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyMessage) Reset() {
	*x = ProxyMessage{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyMessage) ProtoMessage() {}

func (x *ProxyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyMessage.ProtoReflect.Descriptor instead.
func (*ProxyMessage) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{11}
}

func (x *ProxyMessage) GetMessage() isProxyMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProxyMessage) GetHello() *ProxyHello {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ProxyMessage) GetPresenceSnapshot() *PresenceSnapshot {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_PresenceSnapshot); ok {
			return x.PresenceSnapshot
		}
	}
	return nil
}

func (x *ProxyMessage) GetRouteRequest() *RouteRequest {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_RouteRequest); ok {
			return x.RouteRequest
		}
	}
	return nil
}

func (x *ProxyMessage) GetPresenceEvent() *PlayerPresenceEvent {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_PresenceEvent); ok {
			return x.PresenceEvent
		}
	}
	return nil
}

func (x *ProxyMessage) GetPlayerCounts() *ServerPlayerCounts {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_PlayerCounts); ok {
			return x.PlayerCounts
		}
	}
	return nil
}

func (x *ProxyMessage) GetMoveResult() *MoveResult {
	if x != nil {
		if x, ok := x.Message.(*ProxyMessage_MoveResult); ok {
			return x.MoveResult
		}
	}
	return nil
}

type isProxyMessage_Message interface {
	isProxyMessage_Message()
}

type ProxyMessage_Hello struct {
	Hello *ProxyHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ProxyMessage_PresenceSnapshot struct {
	PresenceSnapshot *PresenceSnapshot `protobuf:"bytes,2,opt,name=presence_snapshot,json=presenceSnapshot,proto3,oneof"`
}

type ProxyMessage_RouteRequest struct {
	RouteRequest *RouteRequest `protobuf:"bytes,3,opt,name=route_request,json=routeRequest,proto3,oneof"`
}

type ProxyMessage_PresenceEvent struct {
	PresenceEvent *PlayerPresenceEvent `protobuf:"bytes,4,opt,name=presence_event,json=presenceEvent,proto3,oneof"`
}

type ProxyMessage_PlayerCounts struct {
	PlayerCounts *ServerPlayerCounts `protobuf:"bytes,5,opt,name=player_counts,json=playerCounts,proto3,oneof"`
}

type ProxyMessage_MoveResult struct {
	MoveResult *MoveResult `protobuf:"bytes,6,opt,name=move_result,json=moveResult,proto3,oneof"`
}

func (*ProxyMessage_Hello) isProxyMessage_Message() {}

func (*ProxyMessage_PresenceSnapshot) isProxyMessage_Message() {}

func (*ProxyMessage_RouteRequest) isProxyMessage_Message() {}

func (*ProxyMessage_PresenceEvent) isProxyMessage_Message() {}

func (*ProxyMessage_PlayerCounts) isProxyMessage_Message() {}

func (*ProxyMessage_MoveResult) isProxyMessage_Message() {}

// ControllerMessage is anything the controller sends to a proxy.
type ControllerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControllerMessage_ServerSync
	//	*ControllerMessage_RouteResponse
	//	*ControllerMessage_Move
	Message       isControllerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControllerMessage) Reset() {
	*x = ControllerMessage{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControllerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControllerMessage) ProtoMessage() {}

func (x *ControllerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControllerMessage.ProtoReflect.Descriptor instead.
func (*ControllerMessage) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{12}
}

func (x *ControllerMessage) GetMessage() isControllerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControllerMessage) GetServerSync() *ServerSync {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_ServerSync); ok {
			return x.ServerSync
		}
	}
	return nil
}

func (x *ControllerMessage) GetRouteResponse() *RouteResponse {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_RouteResponse); ok {
			return x.RouteResponse
		}
	}
	return nil
}

func (x *ControllerMessage) GetMove() *MoveCommand {
	if x != nil {
		if x, ok := x.Message.(*ControllerMessage_Move); ok {
			return x.Move
		}
	}
	return nil
}

type isControllerMessage_Message interface {
	isControllerMessage_Message()
}

type ControllerMessage_ServerSync struct {
	ServerSync *ServerSync `protobuf:"bytes,1,opt,name=server_sync,json=serverSync,proto3,oneof"`
}

type ControllerMessage_RouteResponse struct {
	RouteResponse *RouteResponse `protobuf:"bytes,2,opt,name=route_response,json=routeResponse,proto3,oneof"`
}

type ControllerMessage_Move struct {
	Move *MoveCommand `protobuf:"bytes,3,opt,name=move,proto3,oneof"`
}

func (*ControllerMessage_ServerSync) isControllerMessage_Message() {}

func (*ControllerMessage_RouteResponse) isControllerMessage_Message() {}

func (*ControllerMessage_Move) isControllerMessage_Message() {}

type PlayerConnection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid       string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	ProxyId          string                 `protobuf:"bytes,2,opt,name=proxy_id,json=proxyId,proto3" json:"proxy_id,omitempty"`
	ServerName       string                 `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	GatewayNamespace string                 `protobuf:"bytes,4,opt,name=gateway_namespace,json=gatewayNamespace,proto3" json:"gateway_namespace,omitempty"`
	GatewayName      string                 `protobuf:"bytes,5,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	ListenerName     string                 `protobuf:"bytes,6,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PlayerConnection) Reset() {
	*x = PlayerConnection{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerConnection) ProtoMessage() {}

func (x *PlayerConnection) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerConnection.ProtoReflect.Descriptor instead.
func (*PlayerConnection) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerConnection) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

func (x *PlayerConnection) GetProxyId() string {
	if x != nil {
		return x.ProxyId
	}
	return ""
}

func (x *PlayerConnection) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PlayerConnection) GetGatewayNamespace() string {
	if x != nil {
		return x.GatewayNamespace
	}
	return ""
}

func (x *PlayerConnection) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *PlayerConnection) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

type GetConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerUuid    string                 `protobuf:"bytes,1,opt,name=player_uuid,json=playerUuid,proto3" json:"player_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionRequest) Reset() {
	*x = GetConnectionRequest{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionRequest) ProtoMessage() {}

func (x *GetConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionRequest) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetConnectionRequest) GetPlayerUuid() string {
	if x != nil {
		return x.PlayerUuid
	}
	return ""
}

type GetConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    *PlayerConnection      `protobuf:"bytes,1,opt,name=connection,proto3,oneof" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectionResponse) Reset() {
	*x = GetConnectionResponse{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionResponse) ProtoMessage() {}

func (x *GetConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionResponse) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{15}
}

func (x *GetConnectionResponse) GetConnection() *PlayerConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type GetPlayersForServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersForServerRequest) Reset() {
	*x = GetPlayersForServerRequest{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersForServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersForServerRequest) ProtoMessage() {}

func (x *GetPlayersForServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersForServerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersForServerRequest) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{16}
}

func (x *GetPlayersForServerRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type GetPlayersForServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*PlayerConnection    `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersForServerResponse) Reset() {
	*x = GetPlayersForServerResponse{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersForServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersForServerResponse) ProtoMessage() {}

func (x *GetPlayersForServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersForServerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayersForServerResponse) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{17}
}

func (x *GetPlayersForServerResponse) GetConnections() []*PlayerConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

type GetPlayersForServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersForServiceRequest) Reset() {
	*x = GetPlayersForServiceRequest{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersForServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersForServiceRequest) ProtoMessage() {}

func (x *GetPlayersForServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersForServiceRequest.ProtoReflect.Descriptor instead.
func (*GetPlayersForServiceRequest) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlayersForServiceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetPlayersForServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPlayersForServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connections   []*PlayerConnection    `protobuf:"bytes,1,rep,name=connections,proto3" json:"connections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayersForServiceResponse) Reset() {
	*x = GetPlayersForServiceResponse{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayersForServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayersForServiceResponse) ProtoMessage() {}

func (x *GetPlayersForServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayersForServiceResponse.ProtoReflect.Descriptor instead.
func (*GetPlayersForServiceResponse) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{19}
}

func (x *GetPlayersForServiceResponse) GetConnections() []*PlayerConnection {
	if x != nil {
		return x.Connections
	}
	return nil
}

var File_network_v1alpha1_api_proto protoreflect.FileDescriptor

const file_network_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"\x1anetwork/v1alpha1/api.proto\x12\x10network.v1alpha1\x1a\x1cnetwork/v1alpha1/types.proto\"\xce\x01\n" +
	"\rPlayerContext\x12)\n" +
	"\x10connected_domain\x18\x01 \x01(\tR\x0fconnectedDomain\x12R\n" +
	"\vpermissions\x18\x02 \x03(\v20.network.v1alpha1.PlayerContext.PermissionsEntryR\vpermissions\x1a>\n" +
	"\x10PermissionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\x9c\x01\n" +
	"\n" +
	"ProxyHello\x12\x19\n" +
	"\bproxy_id\x18\x01 \x01(\tR\aproxyId\x12+\n" +
	"\x11gateway_namespace\x18\x02 \x01(\tR\x10gatewayNamespace\x12!\n" +
	"\fgateway_name\x18\x03 \x01(\tR\vgatewayName\x12#\n" +
	"\rlistener_name\x18\x04 \x01(\tR\flistenerName\"\x8c\x01\n" +
	"\rPresenceEntry\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x129\n" +
	"\acontext\x18\x03 \x01(\v2\x1f.network.v1alpha1.PlayerContextR\acontext\"M\n" +
	"\x10PresenceSnapshot\x129\n" +
	"\aplayers\x18\x01 \x03(\v2\x1f.network.v1alpha1.PresenceEntryR\aplayers\"\x8f\x02\n" +
	"\fRouteRequest\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1f\n" +
	"\vplayer_uuid\x18\x02 \x01(\tR\n" +
	"playerUuid\x12/\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1b.network.v1alpha1.RouteKindR\x04kind\x129\n" +
	"\acontext\x18\x04 \x01(\v2\x1f.network.v1alpha1.PlayerContextR\acontext\x123\n" +
	"\x13current_server_name\x18\x05 \x01(\tH\x00R\x11currentServerName\x88\x01\x01B\x16\n" +
	"\x14_current_server_name\"\xda\x01\n" +
	"\rRouteResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12>\n" +
	"\x06result\x18\x02 \x01(\x0e2&.network.v1alpha1.RouteResponse.ResultR\x06result\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\"A\n" +
	"\x06Result\x12\r\n" +
	"\tRESULT_OK\x10\x00\x12\x13\n" +
	"\x0fRESULT_NO_ROUTE\x10\x01\x12\x13\n" +
	"\x0fRESULT_REJECTED\x10\x02\"\x85\x02\n" +
	"\x13PlayerPresenceEvent\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12>\n" +
	"\x04kind\x18\x03 \x01(\x0e2*.network.v1alpha1.PlayerPresenceEvent.KindR\x04kind\x129\n" +
	"\acontext\x18\x04 \x01(\v2\x1f.network.v1alpha1.PlayerContextR\acontext\"1\n" +
	"\x04Kind\x12\x12\n" +
	"\x0eKIND_CONNECTED\x10\x00\x12\x15\n" +
	"\x11KIND_DISCONNECTED\x10\x01\"\xbb\x01\n" +
	"\x12ServerPlayerCounts\x12b\n" +
	"\x10counts_by_server\x18\x01 \x03(\v28.network.v1alpha1.ServerPlayerCounts.CountsByServerEntryR\x0ecountsByServer\x1aA\n" +
	"\x13CountsByServerEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value:\x028\x01\"z\n" +
	"\n" +
	"ServerSync\x129\n" +
	"\aservers\x18\x01 \x03(\v2\x1f.network.v1alpha1.ManagedServerR\aservers\x121\n" +
	"\x14required_permissions\x18\x02 \x03(\tR\x13requiredPermissions\"n\n" +
	"\vMoveCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vplayer_uuid\x18\x02 \x01(\tR\n" +
	"playerUuid\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\"]\n" +
	"\n" +
	"MoveResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xc7\x03\n" +
	"\fProxyMessage\x124\n" +
	"\x05hello\x18\x01 \x01(\v2\x1c.network.v1alpha1.ProxyHelloH\x00R\x05hello\x12Q\n" +
	"\x11presence_snapshot\x18\x02 \x01(\v2\".network.v1alpha1.PresenceSnapshotH\x00R\x10presenceSnapshot\x12E\n" +
	"\rroute_request\x18\x03 \x01(\v2\x1e.network.v1alpha1.RouteRequestH\x00R\frouteRequest\x12N\n" +
	"\x0epresence_event\x18\x04 \x01(\v2%.network.v1alpha1.PlayerPresenceEventH\x00R\rpresenceEvent\x12K\n" +
	"\rplayer_counts\x18\x05 \x01(\v2$.network.v1alpha1.ServerPlayerCountsH\x00R\fplayerCounts\x12?\n" +
	"\vmove_result\x18\x06 \x01(\v2\x1c.network.v1alpha1.MoveResultH\x00R\n" +
	"moveResultB\t\n" +
	"\amessage\"\xde\x01\n" +
	"\x11ControllerMessage\x12?\n" +
	"\vserver_sync\x18\x01 \x01(\v2\x1c.network.v1alpha1.ServerSyncH\x00R\n" +
	"serverSync\x12H\n" +
	"\x0eroute_response\x18\x02 \x01(\v2\x1f.network.v1alpha1.RouteResponseH\x00R\rrouteResponse\x123\n" +
	"\x04move\x18\x03 \x01(\v2\x1d.network.v1alpha1.MoveCommandH\x00R\x04moveB\t\n" +
	"\amessage\"\xe4\x01\n" +
	"\x10PlayerConnection\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\x12\x19\n" +
	"\bproxy_id\x18\x02 \x01(\tR\aproxyId\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12+\n" +
	"\x11gateway_namespace\x18\x04 \x01(\tR\x10gatewayNamespace\x12!\n" +
	"\fgateway_name\x18\x05 \x01(\tR\vgatewayName\x12#\n" +
	"\rlistener_name\x18\x06 \x01(\tR\flistenerName\"7\n" +
	"\x14GetConnectionRequest\x12\x1f\n" +
	"\vplayer_uuid\x18\x01 \x01(\tR\n" +
	"playerUuid\"o\n" +
	"\x15GetConnectionResponse\x12G\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2\".network.v1alpha1.PlayerConnectionH\x00R\n" +
	"connection\x88\x01\x01B\r\n" +
	"\v_connection\"=\n" +
	"\x1aGetPlayersForServerRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\"c\n" +
	"\x1bGetPlayersForServerResponse\x12D\n" +
	"\vconnections\x18\x01 \x03(\v2\".network.v1alpha1.PlayerConnectionR\vconnections\"O\n" +
	"\x1bGetPlayersForServiceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"d\n" +
	"\x1cGetPlayersForServiceResponse\x12D\n" +
	"\vconnections\x18\x01 \x03(\v2\".network.v1alpha1.PlayerConnectionR\vconnections*9\n" +
	"\tRouteKind\x12\x13\n" +
	"\x0fROUTE_KIND_JOIN\x10\x00\x12\x17\n" +
	"\x13ROUTE_KIND_FALLBACK\x10\x012`\n" +
	"\n" +
	"NetworkXDS\x12R\n" +
	"\aConnect\x12\x1e.network.v1alpha1.ProxyMessage\x1a#.network.v1alpha1.ControllerMessage(\x010\x012\xdd\x02\n" +
	"\x0eNetworkGateway\x12`\n" +
	"\rGetConnection\x12&.network.v1alpha1.GetConnectionRequest\x1a'.network.v1alpha1.GetConnectionResponse\x12r\n" +
	"\x13GetPlayersForServer\x12,.network.v1alpha1.GetPlayersForServerRequest\x1a-.network.v1alpha1.GetPlayersForServerResponse\x12u\n" +
	"\x14GetPlayersForService\x12-.network.v1alpha1.GetPlayersForServiceRequest\x1a..network.v1alpha1.GetPlayersForServiceResponseBl\n" +
	"-dev.minefleet.api.gateway.networking.v1alpha1Z;github.com/minefleet/minecraft-gateway/api/network/v1alpha1b\x06proto3"

var (
	file_network_v1alpha1_api_proto_rawDescOnce sync.Once
	file_network_v1alpha1_api_proto_rawDescData []byte
)

func file_network_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_network_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_network_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1alpha1_api_proto_rawDesc), len(file_network_v1alpha1_api_proto_rawDesc)))
	})
	return file_network_v1alpha1_api_proto_rawDescData
}

var file_network_v1alpha1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_network_v1alpha1_api_proto_goTypes = []any{
	(RouteKind)(0),                       // 0: network.v1alpha1.RouteKind
	(RouteResponse_Result)(0),            // 1: network.v1alpha1.RouteResponse.Result
	(PlayerPresenceEvent_Kind)(0),        // 2: network.v1alpha1.PlayerPresenceEvent.Kind
	(*PlayerContext)(nil),                // 3: network.v1alpha1.PlayerContext
	(*ProxyHello)(nil),                   // 4: network.v1alpha1.ProxyHello
	(*PresenceEntry)(nil),                // 5: network.v1alpha1.PresenceEntry
	(*PresenceSnapshot)(nil),             // 6: network.v1alpha1.PresenceSnapshot
	(*RouteRequest)(nil),                 // 7: network.v1alpha1.RouteRequest
	(*RouteResponse)(nil),                // 8: network.v1alpha1.RouteResponse
	(*PlayerPresenceEvent)(nil),          // 9: network.v1alpha1.PlayerPresenceEvent
	(*ServerPlayerCounts)(nil),           // 10: network.v1alpha1.ServerPlayerCounts
	(*ServerSync)(nil),                   // 11: network.v1alpha1.ServerSync
	(*MoveCommand)(nil),                  // 12: network.v1alpha1.MoveCommand
	(*MoveResult)(nil),                   // 13: network.v1alpha1.MoveResult
	(*ProxyMessage)(nil),                 // 14: network.v1alpha1.ProxyMessage
	(*ControllerMessage)(nil),            // 15: network.v1alpha1.ControllerMessage
	(*PlayerConnection)(nil),             // 16: network.v1alpha1.PlayerConnection
	(*GetConnectionRequest)(nil),         // 17: network.v1alpha1.GetConnectionRequest
	(*GetConnectionResponse)(nil),        // 18: network.v1alpha1.GetConnectionResponse
	(*GetPlayersForServerRequest)(nil),   // 19: network.v1alpha1.GetPlayersForServerRequest
	(*GetPlayersForServerResponse)(nil),  // 20: network.v1alpha1.GetPlayersForServerResponse
	(*GetPlayersForServiceRequest)(nil),  // 21: network.v1alpha1.GetPlayersForServiceRequest
	(*GetPlayersForServiceResponse)(nil), // 22: network.v1alpha1.GetPlayersForServiceResponse
	nil,                                  // 23: network.v1alpha1.PlayerContext.PermissionsEntry
	nil,                                  // 24: network.v1alpha1.ServerPlayerCounts.CountsByServerEntry
	(*ManagedServer)(nil),                // 25: network.v1alpha1.ManagedServer
}
var file_network_v1alpha1_api_proto_depIdxs = []int32{
	23, // 0: network.v1alpha1.PlayerContext.permissions:type_name -> network.v1alpha1.PlayerContext.PermissionsEntry
	3,  // 1: network.v1alpha1.PresenceEntry.context:type_name -> network.v1alpha1.PlayerContext
	5,  // 2: network.v1alpha1.PresenceSnapshot.players:type_name -> network.v1alpha1.PresenceEntry
	0,  // 3: network.v1alpha1.RouteRequest.kind:type_name -> network.v1alpha1.RouteKind
	3,  // 4: network.v1alpha1.RouteRequest.context:type_name -> network.v1alpha1.PlayerContext
	1,  // 5: network.v1alpha1.RouteResponse.result:type_name -> network.v1alpha1.RouteResponse.Result
	2,  // 6: network.v1alpha1.PlayerPresenceEvent.kind:type_name -> network.v1alpha1.PlayerPresenceEvent.Kind
	3,  // 7: network.v1alpha1.PlayerPresenceEvent.context:type_name -> network.v1alpha1.PlayerContext
	24, // 8: network.v1alpha1.ServerPlayerCounts.counts_by_server:type_name -> network.v1alpha1.ServerPlayerCounts.CountsByServerEntry
	25, // 9: network.v1alpha1.ServerSync.servers:type_name -> network.v1alpha1.ManagedServer
	4,  // 10: network.v1alpha1.ProxyMessage.hello:type_name -> network.v1alpha1.ProxyHello
	6,  // 11: network.v1alpha1.ProxyMessage.presence_snapshot:type_name -> network.v1alpha1.PresenceSnapshot
	7,  // 12: network.v1alpha1.ProxyMessage.route_request:type_name -> network.v1alpha1.RouteRequest
	9,  // 13: network.v1alpha1.ProxyMessage.presence_event:type_name -> network.v1alpha1.PlayerPresenceEvent
	10, // 14: network.v1alpha1.ProxyMessage.player_counts:type_name -> network.v1alpha1.ServerPlayerCounts
	13, // 15: network.v1alpha1.ProxyMessage.move_result:type_name -> network.v1alpha1.MoveResult
	11, // 16: network.v1alpha1.ControllerMessage.server_sync:type_name -> network.v1alpha1.ServerSync
	8,  // 17: network.v1alpha1.ControllerMessage.route_response:type_name -> network.v1alpha1.RouteResponse
	12, // 18: network.v1alpha1.ControllerMessage.move:type_name -> network.v1alpha1.MoveCommand
	16, // 19: network.v1alpha1.GetConnectionResponse.connection:type_name -> network.v1alpha1.PlayerConnection
	16, // 20: network.v1alpha1.GetPlayersForServerResponse.connections:type_name -> network.v1alpha1.PlayerConnection
	16, // 21: network.v1alpha1.GetPlayersForServiceResponse.connections:type_name -> network.v1alpha1.PlayerConnection
	14, // 22: network.v1alpha1.NetworkXDS.Connect:input_type -> network.v1alpha1.ProxyMessage
	17, // 23: network.v1alpha1.NetworkGateway.GetConnection:input_type -> network.v1alpha1.GetConnectionRequest
	19, // 24: network.v1alpha1.NetworkGateway.GetPlayersForServer:input_type -> network.v1alpha1.GetPlayersForServerRequest
	21, // 25: network.v1alpha1.NetworkGateway.GetPlayersForService:input_type -> network.v1alpha1.GetPlayersForServiceRequest
	15, // 26: network.v1alpha1.NetworkXDS.Connect:output_type -> network.v1alpha1.ControllerMessage
	18, // 27: network.v1alpha1.NetworkGateway.GetConnection:output_type -> network.v1alpha1.GetConnectionResponse
	20, // 28: network.v1alpha1.NetworkGateway.GetPlayersForServer:output_type -> network.v1alpha1.GetPlayersForServerResponse
	22, // 29: network.v1alpha1.NetworkGateway.GetPlayersForService:output_type -> network.v1alpha1.GetPlayersForServiceResponse
	26, // [26:30] is the sub-list for method output_type
	22, // [22:26] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_network_v1alpha1_api_proto_init() }
func file_network_v1alpha1_api_proto_init() {
	if File_network_v1alpha1_api_proto != nil {
		return
	}
	file_network_v1alpha1_types_proto_init()
	file_network_v1alpha1_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_network_v1alpha1_api_proto_msgTypes[11].OneofWrappers = []any{
		(*ProxyMessage_Hello)(nil),
		(*ProxyMessage_PresenceSnapshot)(nil),
		(*ProxyMessage_RouteRequest)(nil),
		(*ProxyMessage_PresenceEvent)(nil),
		(*ProxyMessage_PlayerCounts)(nil),
		(*ProxyMessage_MoveResult)(nil),
	}
	file_network_v1alpha1_api_proto_msgTypes[12].OneofWrappers = []any{
		(*ControllerMessage_ServerSync)(nil),
		(*ControllerMessage_RouteResponse)(nil),
		(*ControllerMessage_Move)(nil),
	}
	file_network_v1alpha1_api_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1alpha1_api_proto_rawDesc), len(file_network_v1alpha1_api_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_network_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_network_v1alpha1_api_proto_depIdxs,
		EnumInfos:         file_network_v1alpha1_api_proto_enumTypes,
		MessageInfos:      file_network_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_network_v1alpha1_api_proto = out.File
	file_network_v1alpha1_api_proto_goTypes = nil
	file_network_v1alpha1_api_proto_depIdxs = nil
}
