// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: network/v1alpha1/api.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSnapshotRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GatewayNamespace string                 `protobuf:"bytes,1,opt,name=gateway_namespace,json=gatewayNamespace,proto3" json:"gateway_namespace,omitempty"`
	GatewayName      string                 `protobuf:"bytes,2,opt,name=gateway_name,json=gatewayName,proto3" json:"gateway_name,omitempty"`
	ListenerName     string                 `protobuf:"bytes,3,opt,name=listener_name,json=listenerName,proto3" json:"listener_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetSnapshotRequest) GetGatewayNamespace() string {
	if x != nil {
		return x.GatewayNamespace
	}
	return ""
}

func (x *GetSnapshotRequest) GetGatewayName() string {
	if x != nil {
		return x.GatewayName
	}
	return ""
}

func (x *GetSnapshotRequest) GetListenerName() string {
	if x != nil {
		return x.ListenerName
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_network_v1alpha1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

var File_network_v1alpha1_api_proto protoreflect.FileDescriptor

const file_network_v1alpha1_api_proto_rawDesc = "" +
	"\n" +
	"\x1anetwork/v1alpha1/api.proto\x12\x10network.v1alpha1\x1a\x1cnetwork/v1alpha1/types.proto\"\x89\x01\n" +
	"\x12GetSnapshotRequest\x12+\n" +
	"\x11gateway_namespace\x18\x01 \x01(\tR\x10gatewayNamespace\x12!\n" +
	"\fgateway_name\x18\x02 \x01(\tR\vgatewayName\x12#\n" +
	"\rlistener_name\x18\x03 \x01(\tR\flistenerName\"M\n" +
	"\x13GetSnapshotResponse\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x1a.network.v1alpha1.SnapshotR\bsnapshot2h\n" +
	"\n" +
	"NetworkXDS\x12Z\n" +
	"\vGetSnapshot\x12$.network.v1alpha1.GetSnapshotRequest\x1a%.network.v1alpha1.GetSnapshotResponseBl\n" +
	"-dev.minefleet.api.gateway.networking.v1alpha1Z;github.com/minefleet/minecraft-gateway/api/network/v1alpha1b\x06proto3"

var (
	file_network_v1alpha1_api_proto_rawDescOnce sync.Once
	file_network_v1alpha1_api_proto_rawDescData []byte
)

func file_network_v1alpha1_api_proto_rawDescGZIP() []byte {
	file_network_v1alpha1_api_proto_rawDescOnce.Do(func() {
		file_network_v1alpha1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1alpha1_api_proto_rawDesc), len(file_network_v1alpha1_api_proto_rawDesc)))
	})
	return file_network_v1alpha1_api_proto_rawDescData
}

var file_network_v1alpha1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_v1alpha1_api_proto_goTypes = []any{
	(*GetSnapshotRequest)(nil),  // 0: network.v1alpha1.GetSnapshotRequest
	(*GetSnapshotResponse)(nil), // 1: network.v1alpha1.GetSnapshotResponse
	(*Snapshot)(nil),            // 2: network.v1alpha1.Snapshot
}
var file_network_v1alpha1_api_proto_depIdxs = []int32{
	2, // 0: network.v1alpha1.GetSnapshotResponse.snapshot:type_name -> network.v1alpha1.Snapshot
	0, // 1: network.v1alpha1.NetworkXDS.GetSnapshot:input_type -> network.v1alpha1.GetSnapshotRequest
	1, // 2: network.v1alpha1.NetworkXDS.GetSnapshot:output_type -> network.v1alpha1.GetSnapshotResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_network_v1alpha1_api_proto_init() }
func file_network_v1alpha1_api_proto_init() {
	if File_network_v1alpha1_api_proto != nil {
		return
	}
	file_network_v1alpha1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1alpha1_api_proto_rawDesc), len(file_network_v1alpha1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_v1alpha1_api_proto_goTypes,
		DependencyIndexes: file_network_v1alpha1_api_proto_depIdxs,
		MessageInfos:      file_network_v1alpha1_api_proto_msgTypes,
	}.Build()
	File_network_v1alpha1_api_proto = out.File
	file_network_v1alpha1_api_proto_goTypes = nil
	file_network_v1alpha1_api_proto_depIdxs = nil
}
