// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: network/v1alpha1/api.proto

package v1alpha1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// NetworkDataplaneClient is the client API for NetworkDataplane service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetworkDataplaneClient interface {
}

type networkDataplaneClient struct {
	cc grpc.ClientConnInterface
}

func NewNetworkDataplaneClient(cc grpc.ClientConnInterface) NetworkDataplaneClient {
	return &networkDataplaneClient{cc}
}

// NetworkDataplaneServer is the server API for NetworkDataplane service.
// All implementations must embed UnimplementedNetworkDataplaneServer
// for forward compatibility.
type NetworkDataplaneServer interface {
	mustEmbedUnimplementedNetworkDataplaneServer()
}

// UnimplementedNetworkDataplaneServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNetworkDataplaneServer struct{}

func (UnimplementedNetworkDataplaneServer) mustEmbedUnimplementedNetworkDataplaneServer() {}
func (UnimplementedNetworkDataplaneServer) testEmbeddedByValue()                          {}

// UnsafeNetworkDataplaneServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetworkDataplaneServer will
// result in compilation errors.
type UnsafeNetworkDataplaneServer interface {
	mustEmbedUnimplementedNetworkDataplaneServer()
}

func RegisterNetworkDataplaneServer(s grpc.ServiceRegistrar, srv NetworkDataplaneServer) {
	// If the following call pancis, it indicates UnimplementedNetworkDataplaneServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NetworkDataplane_ServiceDesc, srv)
}

// NetworkDataplane_ServiceDesc is the grpc.ServiceDesc for NetworkDataplane service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetworkDataplane_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1alpha1.NetworkDataplane",
	HandlerType: (*NetworkDataplaneServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "network/v1alpha1/api.proto",
}
