// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: network/v1alpha1/types.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistributionStrategy int32

const (
	DistributionStrategy_RANDOM        DistributionStrategy = 0
	DistributionStrategy_LEAST_PLAYERS DistributionStrategy = 1
)

// Enum value maps for DistributionStrategy.
var (
	DistributionStrategy_name = map[int32]string{
		0: "RANDOM",
		1: "LEAST_PLAYERS",
	}
	DistributionStrategy_value = map[string]int32{
		"RANDOM":        0,
		"LEAST_PLAYERS": 1,
	}
)

func (x DistributionStrategy) Enum() *DistributionStrategy {
	p := new(DistributionStrategy)
	*p = x
	return p
}

func (x DistributionStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DistributionStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1alpha1_types_proto_enumTypes[0].Descriptor()
}

func (DistributionStrategy) Type() protoreflect.EnumType {
	return &file_network_v1alpha1_types_proto_enumTypes[0]
}

func (x DistributionStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DistributionStrategy.Descriptor instead.
func (DistributionStrategy) EnumDescriptor() ([]byte, []int) {
	return file_network_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

type ManagedServer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UniqueId       string                 `protobuf:"bytes,1,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ip             string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port           uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	NumericalId    *uint32                `protobuf:"varint,5,opt,name=numerical_id,json=numericalId,proto3,oneof" json:"numerical_id,omitempty"`
	MaxPlayers     *uint32                `protobuf:"varint,6,opt,name=max_players,json=maxPlayers,proto3,oneof" json:"max_players,omitempty"`
	CurrentPlayers *uint32                `protobuf:"varint,7,opt,name=current_players,json=currentPlayers,proto3,oneof" json:"current_players,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ManagedServer) Reset() {
	*x = ManagedServer{}
	mi := &file_network_v1alpha1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagedServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagedServer) ProtoMessage() {}

func (x *ManagedServer) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1alpha1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagedServer.ProtoReflect.Descriptor instead.
func (*ManagedServer) Descriptor() ([]byte, []int) {
	return file_network_v1alpha1_types_proto_rawDescGZIP(), []int{0}
}

func (x *ManagedServer) GetUniqueId() string {
	if x != nil {
		return x.UniqueId
	}
	return ""
}

func (x *ManagedServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ManagedServer) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ManagedServer) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ManagedServer) GetNumericalId() uint32 {
	if x != nil && x.NumericalId != nil {
		return *x.NumericalId
	}
	return 0
}

func (x *ManagedServer) GetMaxPlayers() uint32 {
	if x != nil && x.MaxPlayers != nil {
		return *x.MaxPlayers
	}
	return 0
}

func (x *ManagedServer) GetCurrentPlayers() uint32 {
	if x != nil && x.CurrentPlayers != nil {
		return *x.CurrentPlayers
	}
	return 0
}

var File_network_v1alpha1_types_proto protoreflect.FileDescriptor

const file_network_v1alpha1_types_proto_rawDesc = "" +
	"\n" +
	"\x1cnetwork/v1alpha1/types.proto\x12\x10network.v1alpha1\"\x95\x02\n" +
	"\rManagedServer\x12\x1b\n" +
	"\tunique_id\x18\x01 \x01(\tR\buniqueId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12&\n" +
	"\fnumerical_id\x18\x05 \x01(\rH\x00R\vnumericalId\x88\x01\x01\x12$\n" +
	"\vmax_players\x18\x06 \x01(\rH\x01R\n" +
	"maxPlayers\x88\x01\x01\x12,\n" +
	"\x0fcurrent_players\x18\a \x01(\rH\x02R\x0ecurrentPlayers\x88\x01\x01B\x0f\n" +
	"\r_numerical_idB\x0e\n" +
	"\f_max_playersB\x12\n" +
	"\x10_current_players*5\n" +
	"\x14DistributionStrategy\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x00\x12\x11\n" +
	"\rLEAST_PLAYERS\x10\x01Bl\n" +
	"-dev.minefleet.api.gateway.networking.v1alpha1Z;github.com/minefleet/minecraft-gateway/api/network/v1alpha1b\x06proto3"

var (
	file_network_v1alpha1_types_proto_rawDescOnce sync.Once
	file_network_v1alpha1_types_proto_rawDescData []byte
)

func file_network_v1alpha1_types_proto_rawDescGZIP() []byte {
	file_network_v1alpha1_types_proto_rawDescOnce.Do(func() {
		file_network_v1alpha1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1alpha1_types_proto_rawDesc), len(file_network_v1alpha1_types_proto_rawDesc)))
	})
	return file_network_v1alpha1_types_proto_rawDescData
}

var file_network_v1alpha1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_v1alpha1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_network_v1alpha1_types_proto_goTypes = []any{
	(DistributionStrategy)(0), // 0: network.v1alpha1.DistributionStrategy
	(*ManagedServer)(nil),     // 1: network.v1alpha1.ManagedServer
}
var file_network_v1alpha1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_network_v1alpha1_types_proto_init() }
func file_network_v1alpha1_types_proto_init() {
	if File_network_v1alpha1_types_proto != nil {
		return
	}
	file_network_v1alpha1_types_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1alpha1_types_proto_rawDesc), len(file_network_v1alpha1_types_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_v1alpha1_types_proto_goTypes,
		DependencyIndexes: file_network_v1alpha1_types_proto_depIdxs,
		EnumInfos:         file_network_v1alpha1_types_proto_enumTypes,
		MessageInfos:      file_network_v1alpha1_types_proto_msgTypes,
	}.Build()
	File_network_v1alpha1_types_proto = out.File
	file_network_v1alpha1_types_proto_goTypes = nil
	file_network_v1alpha1_types_proto_depIdxs = nil
}
