apiVersion: v1
kind: Service
metadata:
  name: edge-xds
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: minecraft-gateway
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: minecraft-gateway
  ports:
    - name: edge-xds
      port: 18000
      targetPort: 18000