---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gateway.networking.dev.minefleet
  resources:
  - minecraftfallbackroutes
  - minecraftgateways
  - minecraftserverdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.dev.minefleet
  resources:
  - minecraftfallbackroutes/finalizers
  - minecraftgateways/finalizers
  - minecraftserverdiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.dev.minefleet
  resources:
  - minecraftfallbackroutes/status
  - minecraftgateways/status
  - minecraftserverdiscoveries/status
  verbs:
  - get
  - patch
  - update
