---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - gateway.networking.minefleet.dev
  resources:
  - minecraftfallbackroutes
  - minecraftjoinroutes
  - minecraftserverdiscoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.minefleet.dev
  resources:
  - minecraftfallbackroutes/finalizers
  - minecraftjoinroutes/finalizers
  - minecraftserverdiscoveries/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.minefleet.dev
  resources:
  - minecraftfallbackroutes/status
  - minecraftjoinroutes/status
  - minecraftserverdiscoveries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.sigs.k8s.io
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.sigs.k8s.io
  resources:
  - gatewayclasses/finalizers
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.sigs.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  verbs:
  - get
  - patch
  - update
