// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: network/v1alpha1/types.proto
// Protobuf Java Version: 4.36.1

package dev.minefleet.api.gateway.networking.v1alpha1;

@com.google.protobuf.Generated
public final class Types extends com.google.protobuf.GeneratedFile {
  private Types() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "Types");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code network.v1alpha1.DistributionStrategy}
   */
  public enum DistributionStrategy
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RANDOM = 0;</code>
     */
    RANDOM(0),
    /**
     * <code>LEAST_PLAYERS = 1;</code>
     */
    LEAST_PLAYERS(1),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "DistributionStrategy");
    }
    /**
     * <code>RANDOM = 0;</code>
     */
    public static final int RANDOM_VALUE = 0;
    /**
     * <code>LEAST_PLAYERS = 1;</code>
     */
    public static final int LEAST_PLAYERS_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DistributionStrategy valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static DistributionStrategy forNumber(int value) {
      switch (value) {
        case 0: return RANDOM;
        case 1: return LEAST_PLAYERS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DistributionStrategy>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DistributionStrategy> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DistributionStrategy>() {
            public DistributionStrategy findValueByNumber(int number) {
              return DistributionStrategy.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return dev.minefleet.api.gateway.networking.v1alpha1.Types.getDescriptor().getEnumType(0);
    }

    private static final DistributionStrategy[] VALUES = values();

    public static DistributionStrategy valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DistributionStrategy(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:network.v1alpha1.DistributionStrategy)
  }

  public interface ManagedServerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:network.v1alpha1.ManagedServer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
     * @return The uniqueId.
     */
    java.lang.String getUniqueId();
    /**
     * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
     * @return The bytes for uniqueId.
     */
    com.google.protobuf.ByteString
        getUniqueIdBytes();

    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string ip = 3 [json_name = "ip"];</code>
     * @return The ip.
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 3 [json_name = "ip"];</code>
     * @return The bytes for ip.
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>uint32 port = 4 [json_name = "port"];</code>
     * @return The port.
     */
    int getPort();

    /**
     * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
     * @return Whether the numericalId field is set.
     */
    boolean hasNumericalId();
    /**
     * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
     * @return The numericalId.
     */
    int getNumericalId();

    /**
     * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
     * @return Whether the maxPlayers field is set.
     */
    boolean hasMaxPlayers();
    /**
     * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
     * @return The maxPlayers.
     */
    int getMaxPlayers();

    /**
     * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
     * @return Whether the currentPlayers field is set.
     */
    boolean hasCurrentPlayers();
    /**
     * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
     * @return The currentPlayers.
     */
    int getCurrentPlayers();
  }
  /**
   * Protobuf type {@code network.v1alpha1.ManagedServer}
   */
  public static final class ManagedServer extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:network.v1alpha1.ManagedServer)
      ManagedServerOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 36,
        /* patch= */ 1,
        /* suffix= */ "",
        "ManagedServer");
    }
    // Use ManagedServer.newBuilder() to construct.
    private ManagedServer(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ManagedServer() {
      uniqueId_ = "";
      name_ = "";
      ip_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.class, dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.Builder.class);
    }

    private int bitField0_;
    public static final int UNIQUE_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uniqueId_ = "";
    /**
     * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
     * @return The uniqueId.
     */
    @java.lang.Override
    public java.lang.String getUniqueId() {
      java.lang.Object ref = uniqueId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uniqueId_ = s;
        return s;
      }
    }
    /**
     * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
     * @return The bytes for uniqueId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUniqueIdBytes() {
      java.lang.Object ref = uniqueId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uniqueId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IP_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ip_ = "";
    /**
     * <code>string ip = 3 [json_name = "ip"];</code>
     * @return The ip.
     */
    @java.lang.Override
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 3 [json_name = "ip"];</code>
     * @return The bytes for ip.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 4;
    private int port_ = 0;
    /**
     * <code>uint32 port = 4 [json_name = "port"];</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }

    public static final int NUMERICAL_ID_FIELD_NUMBER = 5;
    private int numericalId_ = 0;
    /**
     * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
     * @return Whether the numericalId field is set.
     */
    @java.lang.Override
    public boolean hasNumericalId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
     * @return The numericalId.
     */
    @java.lang.Override
    public int getNumericalId() {
      return numericalId_;
    }

    public static final int MAX_PLAYERS_FIELD_NUMBER = 6;
    private int maxPlayers_ = 0;
    /**
     * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
     * @return Whether the maxPlayers field is set.
     */
    @java.lang.Override
    public boolean hasMaxPlayers() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
     * @return The maxPlayers.
     */
    @java.lang.Override
    public int getMaxPlayers() {
      return maxPlayers_;
    }

    public static final int CURRENT_PLAYERS_FIELD_NUMBER = 7;
    private int currentPlayers_ = 0;
    /**
     * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
     * @return Whether the currentPlayers field is set.
     */
    @java.lang.Override
    public boolean hasCurrentPlayers() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
     * @return The currentPlayers.
     */
    @java.lang.Override
    public int getCurrentPlayers() {
      return currentPlayers_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uniqueId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uniqueId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ip_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, ip_);
      }
      if (port_ != 0) {
        output.writeUInt32(4, port_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(5, numericalId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(6, maxPlayers_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(7, currentPlayers_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uniqueId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uniqueId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(ip_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, ip_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, port_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, numericalId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, maxPlayers_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, currentPlayers_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer)) {
        return super.equals(obj);
      }
      dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer other = (dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer) obj;

      if (!getUniqueId()
          .equals(other.getUniqueId())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getIp()
          .equals(other.getIp())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (hasNumericalId() != other.hasNumericalId()) return false;
      if (hasNumericalId()) {
        if (getNumericalId()
            != other.getNumericalId()) return false;
      }
      if (hasMaxPlayers() != other.hasMaxPlayers()) return false;
      if (hasMaxPlayers()) {
        if (getMaxPlayers()
            != other.getMaxPlayers()) return false;
      }
      if (hasCurrentPlayers() != other.hasCurrentPlayers()) return false;
      if (hasCurrentPlayers()) {
        if (getCurrentPlayers()
            != other.getCurrentPlayers()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UNIQUE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUniqueId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      if (hasNumericalId()) {
        hash = (37 * hash) + NUMERICAL_ID_FIELD_NUMBER;
        hash = (53 * hash) + getNumericalId();
      }
      if (hasMaxPlayers()) {
        hash = (37 * hash) + MAX_PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getMaxPlayers();
      }
      if (hasCurrentPlayers()) {
        hash = (37 * hash) + CURRENT_PLAYERS_FIELD_NUMBER;
        hash = (53 * hash) + getCurrentPlayers();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code network.v1alpha1.ManagedServer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:network.v1alpha1.ManagedServer)
        dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.class, dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.Builder.class);
      }

      // Construct using dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uniqueId_ = "";
        name_ = "";
        ip_ = "";
        port_ = 0;
        numericalId_ = 0;
        maxPlayers_ = 0;
        currentPlayers_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dev.minefleet.api.gateway.networking.v1alpha1.Types.internal_static_network_v1alpha1_ManagedServer_descriptor;
      }

      @java.lang.Override
      public dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer getDefaultInstanceForType() {
        return dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.getDefaultInstance();
      }

      @java.lang.Override
      public dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer build() {
        dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer buildPartial() {
        dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer result = new dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uniqueId_ = uniqueId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.ip_ = ip_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.port_ = port_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.numericalId_ = numericalId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.maxPlayers_ = maxPlayers_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.currentPlayers_ = currentPlayers_;
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer) {
          return mergeFrom((dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer other) {
        if (other == dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer.getDefaultInstance()) return this;
        if (!other.getUniqueId().isEmpty()) {
          uniqueId_ = other.uniqueId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.hasNumericalId()) {
          setNumericalId(other.getNumericalId());
        }
        if (other.hasMaxPlayers()) {
          setMaxPlayers(other.getMaxPlayers());
        }
        if (other.hasCurrentPlayers()) {
          setCurrentPlayers(other.getCurrentPlayers());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java.util.Objects.requireNonNull(extensionRegistry);
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uniqueId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                ip_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                port_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                numericalId_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                maxPlayers_ = input.readUInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                currentPlayers_ = input.readUInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uniqueId_ = "";
      /**
       * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
       * @return The uniqueId.
       */
      public java.lang.String getUniqueId() {
        java.lang.Object ref = uniqueId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uniqueId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
       * @return The bytes for uniqueId.
       */
      public com.google.protobuf.ByteString
          getUniqueIdBytes() {
        java.lang.Object ref = uniqueId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uniqueId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
       * @param value The uniqueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqueId(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        uniqueId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearUniqueId() {
        uniqueId_ = getDefaultInstance().getUniqueId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string unique_id = 1 [json_name = "uniqueId"];</code>
       * @param value The bytes for uniqueId to set.
       * @return This builder for chaining.
       */
      public Builder setUniqueIdBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        uniqueId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2 [json_name = "name"];</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 3 [json_name = "ip"];</code>
       * @return The ip.
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 3 [json_name = "ip"];</code>
       * @return The bytes for ip.
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 3 [json_name = "ip"];</code>
       * @param value The ip to set.
       * @return This builder for chaining.
       */
      public Builder setIp(
          java.lang.String value) {
        java.util.Objects.requireNonNull(value);
        ip_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3 [json_name = "ip"];</code>
       * @return This builder for chaining.
       */
      public Builder clearIp() {
        ip_ = getDefaultInstance().getIp();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 3 [json_name = "ip"];</code>
       * @param value The bytes for ip to set.
       * @return This builder for chaining.
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        java.util.Objects.requireNonNull(value);
        checkByteStringIsUtf8(value);
        ip_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>uint32 port = 4 [json_name = "port"];</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return port_;
      }
      /**
       * <code>uint32 port = 4 [json_name = "port"];</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {

        port_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 port = 4 [json_name = "port"];</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000008);
        port_ = 0;
        onChanged();
        return this;
      }

      private int numericalId_ ;
      /**
       * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
       * @return Whether the numericalId field is set.
       */
      @java.lang.Override
      public boolean hasNumericalId() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
       * @return The numericalId.
       */
      @java.lang.Override
      public int getNumericalId() {
        return numericalId_;
      }
      /**
       * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
       * @param value The numericalId to set.
       * @return This builder for chaining.
       */
      public Builder setNumericalId(int value) {

        numericalId_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 numerical_id = 5 [json_name = "numericalId"];</code>
       * @return This builder for chaining.
       */
      public Builder clearNumericalId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        numericalId_ = 0;
        onChanged();
        return this;
      }

      private int maxPlayers_ ;
      /**
       * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
       * @return Whether the maxPlayers field is set.
       */
      @java.lang.Override
      public boolean hasMaxPlayers() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
       * @return The maxPlayers.
       */
      @java.lang.Override
      public int getMaxPlayers() {
        return maxPlayers_;
      }
      /**
       * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
       * @param value The maxPlayers to set.
       * @return This builder for chaining.
       */
      public Builder setMaxPlayers(int value) {

        maxPlayers_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 max_players = 6 [json_name = "maxPlayers"];</code>
       * @return This builder for chaining.
       */
      public Builder clearMaxPlayers() {
        bitField0_ = (bitField0_ & ~0x00000020);
        maxPlayers_ = 0;
        onChanged();
        return this;
      }

      private int currentPlayers_ ;
      /**
       * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
       * @return Whether the currentPlayers field is set.
       */
      @java.lang.Override
      public boolean hasCurrentPlayers() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
       * @return The currentPlayers.
       */
      @java.lang.Override
      public int getCurrentPlayers() {
        return currentPlayers_;
      }
      /**
       * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
       * @param value The currentPlayers to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentPlayers(int value) {

        currentPlayers_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 current_players = 7 [json_name = "currentPlayers"];</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentPlayers() {
        bitField0_ = (bitField0_ & ~0x00000040);
        currentPlayers_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:network.v1alpha1.ManagedServer)
    }

    // @@protoc_insertion_point(class_scope:network.v1alpha1.ManagedServer)
    private static final dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer();
    }

    public static dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ManagedServer>
        PARSER = new com.google.protobuf.AbstractParser<ManagedServer>() {
      @java.lang.Override
      public ManagedServer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ManagedServer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ManagedServer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public dev.minefleet.api.gateway.networking.v1alpha1.Types.ManagedServer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_network_v1alpha1_ManagedServer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_network_v1alpha1_ManagedServer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034network/v1alpha1/types.proto\022\020network." +
      "v1alpha1\"\225\002\n\rManagedServer\022\033\n\tunique_id\030" +
      "\001 \001(\tR\010uniqueId\022\022\n\004name\030\002 \001(\tR\004name\022\016\n\002i" +
      "p\030\003 \001(\tR\002ip\022\022\n\004port\030\004 \001(\rR\004port\022&\n\014numer" +
      "ical_id\030\005 \001(\rH\000R\013numericalId\210\001\001\022$\n\013max_p" +
      "layers\030\006 \001(\rH\001R\nmaxPlayers\210\001\001\022,\n\017current" +
      "_players\030\007 \001(\rH\002R\016currentPlayers\210\001\001B\017\n\r_" +
      "numerical_idB\016\n\014_max_playersB\022\n\020_current" +
      "_players*5\n\024DistributionStrategy\022\n\n\006RAND" +
      "OM\020\000\022\021\n\rLEAST_PLAYERS\020\001Bl\n-dev.minefleet" +
      ".api.gateway.networking.v1alpha1Z;github" +
      ".com/minefleet/minecraft-gateway/api/net" +
      "work/v1alpha1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_network_v1alpha1_ManagedServer_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_network_v1alpha1_ManagedServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_network_v1alpha1_ManagedServer_descriptor,
        new java.lang.String[] { "UniqueId", "Name", "Ip", "Port", "NumericalId", "MaxPlayers", "CurrentPlayers", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
