apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: minecraft-gateway
    app.kubernetes.io/managed-by: kustomize
  name: network-forwarding-secret
data:
  MF_FORWARDING_SECRET: bWluZWZsZWV0