apiVersion: gateway.networking.minefleet.dev/v1alpha1
kind: MinecraftJoinRoute
metadata:
  labels:
    app.kubernetes.io/name: minecraft-gateway
    app.kubernetes.io/managed-by: kustomize
  name: minecraftjoinroute-game
spec:
  priority: 0
  parentRefs:
    - name: minefleet-gateway-sample
      kind: Gateway
      group: gateway.networking.k8s.io
  hostnames:
  - "play.staging.localhost"
  backendRefs:
    - name: example-gameserver
      port: 25565
  filterRules:
    - type: any
      rules:
        - domain: "play.staging.localhost"