apiVersion: gateway.networking.minefleet.dev/v1
kind: MinecraftFallbackRoute
metadata:
  labels:
    app.kubernetes.io/name: minecraft-gateway
    app.kubernetes.io/managed-by: kustomize
  name: minecraftfallbackroute-sample
spec:
  priority: 0
  parentRefs:
    - name: minefleet-gateway-sample
      kind: Gateway
      group: gateway.networking.k8s.io
  backendRefs:
    - name: minecraft-service-sample
      port: 25565
  filterRules:
    - type: any
      rules:
        - fallbackFor:
            matchLabels:
              minefleet.dev/environment: sample