apiVersion: gateway.networking.dev.minefleet/v1
kind: MinecraftFallbackRoute
metadata:
  labels:
    app.kubernetes.io/name: minecraft-gateway
    app.kubernetes.io/managed-by: kustomize
  name: minecraftfallbackroute-sample
spec:
  # TODO(user): Add fields here
