## Append samples of your project ##
resources:
- gateway.networking_v1_minecraftfallbackroute.yaml
- gateway.networking_v1_minecraftjoinroute.yaml
- gateway.networking_v1_minecraftserverdiscovery.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
